# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-02 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = []
